require 'rake/clean'

40.times do |num|
  sleepval = sprintf("%0.2f",num/100.0)
  taskname = "task_#{num}"
  task taskname do |t|
    ENV['MYNUM'] = num.to_s
    sh "sleep #{sleepval} ; echo ruby-num was #{num} env-num was $MYNUM >> x.tmp"
  end
  task :default => taskname
end

CLEAN.add("x.tmp")
