require 'rake/clean'
CLEAN.add("rf_[a-z].tmp")
verbose(1)

file 'rf_a.tmp' do ; puts "filetask a" ; end 
file 'rf_b.tmp' => 'rf_a.tmp' do ; puts "filetask b" ; end 
file 'rf_c.tmp' => 'rf_b.tmp' do ; puts "filetask c" ; end 
file 'rf_d.tmp' => 'rf_c.tmp' do ; puts "filetask d" ; end 

task :default => 'rf_d.tmp'

task :build do
  ('a'..'d').map { |x| sh "touch rf_#{x}.tmp" }
end

task :rm_middle do
    sh "rm rf_[bc].tmp"
end

task :touchb do ; sh "touch rf_b.tmp" ; end
